arm:
  # You can keep the IKFast or other options commented out if you like
  # kinematics_solver: phantomx_pincher_arm/IKFastKinematicsPlugin
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  position_only_ik: true
  kinematics_solver_attempts: 5
